[workspace]
members = [
  "core",
  "ingester",
  "replayer",
  "strategy",
  "shadow_oms",
  "db",
  "tools/tui",
]

[workspace.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
